"use client";

import "./globals.css";
import { ColorModeContext, useMode } from "./theme";
import { CssBaseline, ThemeProvider, Box } from "@mui/material";
import { Sidebar } from "./components/Sidebar/Sidebar";
import { Topbar } from "./components/Topbar/Topbar";

export const metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [theme, colorMode] = useMode();

  return (
    <html lang="en">
      <body>
        <ColorModeContext.Provider value={colorMode}>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <main className="flex flex-row">
              <Sidebar />
              <Box className="flex flex-col items-stretch w-full" m="20px">
                <Topbar />
                {children}
              </Box>
            </main>
          </ThemeProvider>
        </ColorModeContext.Provider>
      </body>
    </html>
  );
}
